name: PR Linter

on:
  pull_request:
    branches:
      - dev
      - stage
      - master

jobs:
  lint:
    name: Check coding standard
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: ['16.x']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - run: npm run prettier
