name: DEV Auto deploy

on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: Check coding standard
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: ['16.x']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - run: npm run prettier
  build:
    name: Build and deploy to remote host
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          script_stop: true
          script: |
            cd "${{ secrets.SSH_APP_PATH_DEV }}"
            bash git-checkout-branch.sh "${{ github.ref_name }}"
            git pull origin ${{ github.ref_name }}

            export APP_PORT=${{ secrets.APP_PORT_DEV }}
            export INSTANCE_TYPE=${{ secrets.INSTANCE_TYPE_DEV }}

            rm -f .env.production
            echo REACT_APP_X_ORBITER_LIQUIDATOR_API_KEY=${{ secrets.REACT_APP_X_ORBITER_LIQUIDATOR_API_KEY_DEV }} > .env.production
            echo REACT_APP_X_ORBITER_LIQUIDATOR_API_URL=${{ secrets.REACT_APP_X_ORBITER_LIQUIDATOR_API_URL_DEV }} >> .env.production

            export DOCKER_SCAN_SUGGEST=false
            docker compose -f docker-compose.prod.yml up -d --build
